#!/usr/bin/env bash

#
#   Copyright 2014 Fabian "Praetorian" Kürten
#
#   This file is part of praetorian-basics.
#   praetorian-basics program is free software: you can redistribute it
#   and/or modify it under the terms of the GNU General Public License
#   as published by the Free Software Foundation, exactly version 3 of
#   the License.
#
#   praetorian-basics program is distributed in the hope that it will be
#   useful but WITHOUT ANY WARRANTY; without even the implied warranty
#   of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program (COPYING.GPL).  If not, see
#   <http://www.gnu.org/licenses/>.
#

# Configuration section
MODULE_NAME=basics
DEPENDENCIES=
LIBS:=-ldl

$(phony default): library

include scripts/objectsMakeppfile.mk
PROJECT_NAME:=${MODULE_NAME}
include scripts/version.mk

$(phony FORCE):
    @true

global CXXFLAGS+= --std=c++11
global CPPFLAGS:=${CPPFLAGS} -I${CURDIR}/target/generated
ARFLAGS:=crvs

CPPFLAGS+=-I${CURDIR}/../${DEPENDENCIES}/src/main/c++/
LIBS+=$(addprefix -l,${DEPENDENCIES})
LDFLAGS+=-L${CURDIR}/../${DEPENDENCIES}/target/
OWN_LIB_FILES=$(shell ./scripts/expandModules.sh ${DEPENDENCIES})
iftrue ${DEPENDENCIES}
	DEPENDENCY_FILES:=${CURDIR}/../${DEPENDENCIES}/target/dependencies
	DEPLIBS=$(shell cat ${DEPENDENCY_FILES})
else
	DEPENDENCY_FILES:=
	DEPLIBS:=
endif

load_makefile target/objects/Makeppfile
load_makefile ${CURDIR}/../${DEPENDENCIES}

OBJECTS:=$(shell ./scripts/findObjects.sh)
ALLLIBS=${LIBS} ${DEPLIBS}

MODULE_STATIC_LIBRARY:=lib${MODULE_NAME}.a

target/${MODULE_STATIC_LIBRARY}: ${OBJECTS}
	@if [ -e ${output} ]; then rm ${output}; echo "rm ${output}"; fi
	${AR} ${ARFLAGS} ${output} ${OBJECTS}

target/dependencies:
    echo ${ALLLIBS} > ${output}

$(phony library): target/${MODULE_STATIC_LIBRARY}
